name: Build Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: latexmk
          args: -pdf -jobname=Monekli\ Fred\ Dilapisho\ CV

      - name: Upload built PDF
        uses: actions/upload-artifact@v4
        with:
          name: "Monekli Fred Dilapisho CV"
          path: "Monekli Fred Dilapisho CV.pdf"
